<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>出错啦</title>
    <link rel="stylesheet" href="<?php echo Common::getCssUrl('error/base'); ?>">
    <style type="text/css">
    *{margin: 0px; padding: 0px;}
        .clearfix{zoom:1;}
        .clearfix:after{content: '.'; height: 0px; overflow: hidden; clear:both; display: block;}
        .red{color:#cc0000;}
        body{background:-webkit-linear-gradient(top,#e0f8f6,#e5f8f6);
        background:-moz-linear-gradient(top,#e0f8f6,#e5f8f6);
        background:-ms-linear-gradient(top,#e0f8f6,#e5f8f6);
        background:-o-linear-gradient(top,#e0f8f6,#e5f8f6);
        background:linear-gradient(top,#e0f8f6,#e5f8f6);}
        .containter_404{min-width: 1024px; width:100%; /* height:910px; */overflow: hidden;}
        .main_bg{ display: block; width: 437px; height:420px; background: url(/images/error/main_bg.png) no-repeat;  margin-left:20%; margin-top:50px;  float:left; }
        .main{ width:36%; margin:126px auto 0px;  float: left; }
        .tips_404{ font: 24px/32px '微软雅黑'; color:#22976d; }
        .return_main{ display: block; width:144px; height: 75px; background: url(/images/error/return.png) no-repeat; margin-top: 50px; margin-left: 110px;}
        .return_main:hover{background: url(/images/error/return_a.png) no-repeat;}
        .reason_list{ font:14px/28px '微软雅黑'; color:#666;}
        .reason_inner{ color:#20976f;}
        .reason_tips{font:14px/28px '微软雅黑';color:#21986e;}
        .margin_30{ margin-top: 30px;}
    </style>
</head>
<body>
    <div class="containter_404 clearfix">
        <span class="main_bg"></span>
        <div class="main">
            <p class='tips_404'>抱歉 ! 出错了。</p>
            <p class="reason_list margin_30">可能因为：</p>
            <p class="reason_list"><span class="reason_inner">权限分配问题</span>>请确认您所登陆的用户是否有访问此栏目的权限</p>
            <p class="reason_list"><span class="reason_inner">网址输入错误</span>>请检查地址是否完整或存在多余字符</p>
            <p class="reason_tips margin_30">如果您不确定您能访问的后台权限，请点击返回<a class='red' href='/statisticsmanage/login/index'>首页</a>返回后台登陆页面</p>
            <p class="reason_tips">如果有任何意见或建议，请及时反馈给我们（客服电话：021-60161000）。</p>
            <a class="return_main" id="back_forword" href="javascript:;"></a>
        </div>
    </div>
    <script type="text/javascript">
    window.onload=function(){
        var obj=document.getElementById('back_forword');
        obj.onclick=function(){
            window.history.back();
        }
    };
    </script>
</body>
</html>