<?php include_once $this->getScriptPath() . '/header.phtml'; ?>
<?php new Widget_Admin_Left(); ?>
<!-- main -->
<div id="main">
    <div class="main-wrap">

        <div class="title-bar">
            <h3 class="icon-wrap">
                <span class="icon icon-h"></span>
                <span>用户管理</span>
            </h3>
        </div>
        <!-- grids -->
        <div class="grid">
            <!-- 头部功能栏 -->
            <div class="grid-bar">
                <div class="fl">
                </div>
            </div>
            <!-- table -->
            <table class="grid-body">
                <thead>
                    <tr>
                        <!-- <th>
                            <input type="checkbox" nt="checkAll"/>
                        </th> -->
                        <th>ID</th>
                        <th>用户名</th>
                        <th>邮箱</th>
                        <th>手机号码</th>
                        <th>头像</th>
                        <th>是否后台管理员</th>
                    </tr>
                </thead>
                <tbody class="tbd">
                <?php 
                    if ($list) {
                        foreach ($list as $value) { 
                ?>
                    <tr>
                        <!--<td>
                            <input type="checkbox" nt="check" data-id="<?php echo $value['id'] ?>"/>
                        </td>-->
                        <td><?php echo $value['id']; ?></td>
                        <td><?php echo $value['userName']; ?></td>
                        <td><?php echo $value['email']; ?></td>
                        <td><?php echo $value['phone']; ?></td>
                        <td>
                            <?php 
                                echo $value['avatar'] ? '<img src="'. $value['avatar']. '" width="100" />' : ''; 
                            ?>
                        </td>
                        <td><?php echo $value['isAdmin'] ? '是' : '否'; ?></td>
                    </tr>
                <?php }} ?>
                </tbody>
            </table>
        </div>
        <!-- grids end -->
    </div>
</div>
<script type="text/javascript">
    
</script>
<?php include_once $this->getScriptPath() . '/footer.phtml'; ?>