<?php include_once $this->getScriptPath() . '/header.phtml'; ?>
<?php new Widget_Admin_Left(); ?>
<!-- main -->
<div id="main">
    <div class="main-wrap">

        <div class="title-bar">
            <h3 class="icon-wrap">
                <span class="icon icon-h"></span>
                <span>分类管理</span>
            </h3>
        </div>
        <form nt-type="search-form" action="/sites/admin/product/index" method="get">
            <div class="search">
                <div class="line">
                    <label class="field-wrap">
                        <span>顶级分类：</span>
                        <select class="select-field" name="pCid">
                            <option value="">全部</option>
                            <?php if ($category) { foreach ($category as $value) {?>
                            <option <?php echo $value['id'] == $pCid ? 'selected' : ''; ?> value="<?php echo $value['id'] ?>"><?php echo $value['name'] ?></option>
                            <?php }} ?>
                        </select>
                    </label>
                    <label class="field-wrap">
                        <span>子分类：</span>
                        <select class="select-field" name="cCid">
                            <option value="">全部</option>
                            <?php 
                                if ($pCid && isset($category[$pCid]) 
                                                && isset($category[$pCid]['child'])) { 
                                    foreach ($category[$pCid]['child'] as $value) {
                            ?>
                            <option <?php echo $value['id'] == $cCid ? 'selected' : ''; ?> value="<?php echo $value['id'] ?>"><?php echo $value['name'] ?></option>
                            <?php }} ?>
                        </select>
                    </label>
                    <button class="btn search-btn icon-wrap">
                        <span class="icon icon-search"></span>
                        <span>查询</span>
                    </button>
                </div>
            </div>
        </form>
        <!-- grids -->
        <div class="grid">
            <!-- 头部功能栏 -->
            <div class="grid-bar">
                <div class="fl">
                    <button class="btn btn-primary export-btn icon-wrap" nt="addnew">
                        <span class="icon icon-plus"></span>
                        <span>新增作品</span>
                    </button>
                </div>
            </div>
            <!-- table -->
            <table class="grid-body">
                <thead>
                    <tr>
                        <!-- <th>
                            <input type="checkbox" nt="checkAll"/>
                        </th> -->
                        <th width="3%">ID</th>
                        <th width="15%">标题</th>
                        <th width="30%">内容描述</th>
                        <th width="5%">评分</th>
                        <th width="5%">评分人数</th>
                        <th width="5%">文件大小</th>
                        <th width="10%">所属分类</th>
                        <th width="12%">小缩略图</th>
                        <th width="15%">操作</th>
                    </tr>
                </thead>
                <tbody class="tbd">
                <?php 
                    if ($list) {
                        foreach ($list as $value) { 
                ?>
                    <tr>
                        <!--<td>
                            <input type="checkbox" nt="check" data-id="<?php echo $value['id'] ?>"/>
                        </td>-->
                        <td><?php echo $value['id']; ?></td>
                        <td><?php echo $value['title']; ?></td>
                        <td><?php echo $value['description']; ?></td>
                        <td><?php echo $value['avgStar']; ?></td>
                        <td><?php echo $value['totalUserForStar']; ?></td>
                        <td><?php echo $value['fileSize']; ?></td>
                        <td>
                        <?php 
                            if (isset($relationList[$value['id']])) {
                                foreach ($relationList[$value['id']] as $k => $val) {
                                    if (isset($categoryNotSort[$val['categoryId']])) {
                                        $pId = $categoryNotSort[$val['categoryId']]['parentId'];
                                        if (isset($categoryNotSort[$pId])) {
                                            echo $categoryNotSort[$pId]['name']. ':';
                                        }
                                        echo $categoryNotSort[$val['categoryId']]['name']. '<br>';
                                    }
                                }
                            }
                        ?>
                        </td>
                        <td>
                            <?php 
                                $pic = $value['pic']; 
                                echo '<img src="'. $pic['small']. '" style="height:80px;">'; 
                            ?>
                        </td>
                        <td>
                            <a href="javascript:;" class="grid-action icon-wrap" nt="addnew" data-id="<?php echo $value['id'] ?>">
                                <span class="icon icon-edit"></span>
                                <span>编辑</span>
                            </a>
                            <a href="javascript:;" class="grid-action icon-wrap" nt="delete" data-delete="<?php echo $value['id'] ?>">
                                <span class="icon icon-del"></span>
                                <span>删除</span>
                            </a>
                        </td>
                    </tr>
                <?php }} ?>
                </tbody>
            </table>

            <!-- 底部功能栏 -->
            <div class="grid-bar">
                <div class="fr">
                    <?php echo $pageList; ?>
                </div>
            </div>
            <!-- 底部功能栏 end -->
        </div>
        <!-- grids end -->
    </div>
</div>
<script type="text/html" id="dealTpl">
    <form id="dealForm"  data-bind="submit: subForm">
        <ul class="chunk-list search">
            <li class="chunk">
                <label class="left">
                    <span>作品标题：</span>
                </label>
                <div class="right">
                    <input type="text" name="title" class="text-field" placeholder="请输入作品标题" value="${title}" />
                </div>
            </li>
            <li class="chunk">
                <label class="left">
                    <span>作品描述：</span>
                </label>
                <div class="right">
                    <textarea name="description" class="textarea-field" placeholder="请输入作品描述">${description}</textarea>
                </div>
            </li>
            <li class="chunk">
                <label class="left">
                    <span>小缩略图：</span>
                </label>
                <div class="right">
                    <a class="up-file" id="loadsmall" href="javascript:void(0)"></a>
                     {@if small}
                     <img src="${small}" style="width: 150px;" >
                     {@/if}
                </div>
            </li>
            <li class="chunk">
                <label class="left">
                    <span>大缩略图：</span>
                </label>
                <div class="right">
                    <a class="up-file" id="loadbig" href="javascript:void(0)"></a>
                    {@each big as item,index}
                    <img src="${item}" style="height: 100px;margin-right: 5px;" >
                    {@/each}
                </div>
            </li>
            <li class="chunk">
                <label class="left">
                    <span>上传文件：</span>
                </label>
                <div class="right">
                    <a class="up-file" id="loadFile" href="javascript:void(0)"></a>
                    {@if filePath}
                    <a href="${filePath}" >${filePath}</a>
                    {@/if}
                </div>
            </li>
            <li class="chunk">
                <label class="left">
                    <span>作品分类：</span>
                </label>
                <div class="right">
                    <div id="chooseResult" class="chooseResult">
                        {@each tmpClasses as item,index}
                        <span>${item.pName}:${item.name}
                        <i class="cancelIcon" onClick="cancelClasses('${item.id}')">&nbsp;</i>
                        </span>
                        {@/each}
                    </div>
                    <?php 
                        if ($category) {
                            foreach ($category as $key => $value) {

                    ?>
                    <dl id="choose">
                        <dt><?php echo $value['name']. ':'; ?></dt>
                        <?php if (isset($value['child']) && $value['child']) { ?>
                        <dd>
                            <?php foreach ($value['child'] as $k => $val) { ?>
                            <span data-id="<?php echo $val['id']; ?>" data-name="<?php echo $val['name']; ?>" data-pname="<?php echo $value['name']; ?>">
                                <?php echo $val['name']; ?>
                            </span>
                            <?php } ?>
                        </dd>
                        <?php } ?>
                    </dl>
                    <?php }} ?>
                </div>
            </li>
        </ul>
    </form>
</script>
<script type="text/javascript">
    var pItems   = <?php echo $list ? json_encode($list) : 'null'; ?>;
    var cItems   = <?php echo $categoryNotSort ? json_encode($categoryNotSort) : 'null'; ?>;
    var rItems   = <?php echo $relationList ? json_encode($relationList) : 'null'; ?>;
    var category = <?php echo $category ? json_encode($category) : 'null'; ?>;
</script>
<?php include_once $this->getScriptPath() . '/footer.phtml'; ?>