<?php include_once $this->getScriptPath() . '/header.phtml'; ?>
<?php new Widget_Admin_Left(); ?>
<!-- main -->
<div id="main">
    <div class="main-wrap">

        <div style="margin: 0 auto;height: 300px;width: 100%;text-align: center;line-height: 300px;font-size: 40px;">
        	欢迎进入后台管理系统
        </div>
        <!-- grids end -->
    </div>
</div>
<!-- main end -->
<?php include_once $this->getScriptPath() . '/footer.phtml'; ?>